<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>
<center><b><h1>Lab - 1</b></center>    
<center><b><h1>Madhav Lehru - 22010101100</b></center>    
<pre>

## Step 1. Import the necessary libraries

In [1]:
import pandas as pd

## Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [51]:
data = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')
data

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 4. See the first 10 entries

In [4]:
data.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [8]:
data.shape

(4622, 5)

In [9]:
data.shape[0]

4622

### Step 6. What is the number of columns in the dataset?

In [10]:
data.shape[1]

5

### Step 7. Print the name of all the columns.

In [12]:
data.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [13]:
data.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [17]:
data['item_name'].value_counts().idxmax()

'Chicken Bowl'

### Step 10. For the most-ordered item, how many items were ordered?

In [22]:
data['item_name'].value_counts().max()

726

### Step 11. What was the most ordered item in the choice_description column?

In [23]:
data['choice_description'].value_counts().idxmax()

'[Diet Coke]'

### Step 12. How many items were orderd in total?

In [27]:
data.groupby('item_name').sum().sort_values('quantity', ascending=False)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98 $10.98 $11.25 $8.75 $8.49 $11.25 $8.75 ...
Chicken Burrito,497303,591,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49 $8.49 $10.98 $8.49 $10.98 $10.98 $8.75 $...
Chips and Guacamole,449959,506,0,$4.45 $4.45 $4.45 $4.45 $4.45 $3.99 $4.45 $3.9...
Steak Burrito,328437,386,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75 $9.25 $8.99 $11.75 $8.99 $8.99 $8.99 $8...
Canned Soft Drink,304753,351,[Coke][Sprite][Coke][Coke][Lemonade][Sprite][D...,$1.25 $1.25 $1.25 $1.25 $1.25 $1.25 $1.25 $1.2...
Chips,208004,230,0,$2.15 $2.15 $2.15 $2.15 $2.15 $2.15 $4.30 $2.1...
Steak Bowl,193752,221,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.99 $8.99 $11.75 $11.75 $8.99 $11.48 $9.25 $...
Bottled Water,175944,211,0,$1.09 $1.09 $1.09 $1.50 $1.50 $1.50 $3.00 $1.5...
Chips and Fresh Tomato Salsa,100419,130,0,$2.39 $2.39 $2.39 $2.95 $2.95 $2.95 $2.95 $2.3...
Canned Soda,76396,126,[Sprite][Dr. Pepper][Mountain Dew][Sprite][Dr....,$2.18 $1.09 $2.18 $1.09 $1.09 $1.09 $1.09 $2.1...
Chicken Salad Bowl,117104,123,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75 $22.50 $22.50 $8.75 $17.50 $8.75 $8.75 $...
Chicken Soft Tacos,98395,120,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75 $8.75 $8.75 $8.75 $11.25 $8.49 $8.49 $8....
Side of Chips,84769,110,0,$1.69 $1.69 $1.69 $1.69 $1.69 $1.69 $1.69 $1.6...
Veggie Burrito,80962,97,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25 $8.49 $11.25 $11.25 $10.98 $8.49 $8.49 ...
Barbacoa Burrito,74718,91,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99 $9.25 $9.25 $11.75 $11.75 $9.25 $8.99 $1...
Veggie Bowl,72270,87,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25 $8.49 $11.25 $11.25 $8.49 $11.25 $11.25...
Carnitas Bowl,62742,71,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99 $11.75 $9.25 $11.48 $8.99 $8.99 $23.50 $...
Barbacoa Bowl,53972,66,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.75 $11.75 $9.25 $8.99 $9.25 $11.75 $9.25 $...
Carnitas Burrito,51652,60,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99 $9.25 $11.75 $9.25 $9.25 $9.25 $11.75 $9...
Steak Soft Tacos,50177,56,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25 $9.25 $8.99 $9.25 $8.99 $8.99 $9.25 $9.2...
6 Pack Soft Drink,52322,55,[Sprite][Diet Coke][Coke][Diet Coke][Diet Coke...,$6.49 $6.49 $6.49 $6.49 $6.49 $6.49 $6.49 $6.4...
Chips and Tomatillo Red Chili Salsa,45556,50,0,$2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.9...
Chicken Crispy Tacos,47382,50,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75 $17.50 $11.25 $8.49 $8.49 $11.25 $8.75 $...
Chips and Tomatillo Green Chili Salsa,41170,45,0,$2.95 $2.95 $5.90 $2.95 $2.95 $2.95 $2.95 $2.9...
Carnitas Soft Tacos,37673,40,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$9.25 $9.25 $9.25 $9.25 $9.25 $8.99 $8.99 $8.9...
Steak Crispy Tacos,35818,36,"[Fresh Tomato Salsa, Sour Cream][[Roasted Chil...",$9.25 $8.99 $9.25 $8.69 $8.99 $9.25 $8.99 $9.2...
Chips and Tomatillo-Green Chili Salsa,21826,33,0,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
Steak Salad Bowl,29590,31,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",$23.78 $11.89 $9.39 $23.78 $11.89 $11.89 $11.8...
Nantucket Nectar,21814,29,[Apple][Pomegranate Cherry][Pineapple Orange B...,$3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $6.78 $3.3...
Chips and Tomatillo-Red Chili Salsa,18344,25,0,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
Barbacoa Soft Tacos,18725,25,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",$9.25 $9.25 $8.99 $9.25 $9.25 $11.75 $11.75 $9...
Chips and Roasted Chili Corn Salsa,14999,23,0,$2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.95 $2.9...
Izze,10587,20,[Clementine][Grapefruit][Blackberry][Blackberr...,$3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $3.39 $3.3...
Veggie Salad Bowl,17303,18,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25 $11.25 $11.25 $11.25 $8.75 $8.75 $11.25...
Chips and Roasted Chili-Corn Salsa,17462,18,0,$2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.39 $2.3...
Barbacoa Crispy Tacos,5613,12,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$11.75 $9.25 $11.48 $11.75 $9.25 $9.25 $8.99 $...
Barbacoa Salad Bowl,9708,10,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",$11.89 $11.89 $9.39 $9.39 $9.39 $11.89 $11.89 ...
Chicken Salad,10465,9,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$10.98 $10.98 $8.49 $8.49 $8.49 $8.49 $8.49 $8...
Carnitas Crispy Tacos,5868,8,[Roasted Chili Corn Salsa][Tomatillo Green Chi...,$9.25 $11.75 $8.99 $11.75 $8.99 $17.98 $9.25
Veggie Soft Tacos,5520,8,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25 $8.75 $8.49 $11.25 $8.75 $8.49 $16.98
Burrito,1550,6,"[Adobo-Marinated and Grilled Chicken, Pinto Be...",$7.40 $7.40 $7.40 $7.40 $7.40 $7.40
Veggie Salad,7265,6,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.49 $8.49 $8.49 $8.49 $8.49 $8.49
Carnitas Salad Bowl,6693,6,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.89 $9.39 $11.89 $9.39 $11.89 $11.89
Bowl,472,4,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20 $7.40
Steak Salad,2362,4,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99 $8.99 $8.99 $8.69
Salad,1150,2,"[Brown Rice, Adobo-Marinated and Grilled Chick...",$7.40 $7.40
Crispy Tacos,434,2,[Adobo-Marinated and Grilled Steak][Adobo-Mari...,$7.40 $7.40
Chips and Mild Fresh Tomato Salsa,279,1,0,$3.00
Carnitas Salad,1500,1,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.99
Veggie Crispy Tacos,668,1,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49

In [26]:
data['quantity'].sum()

4972

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [28]:
data['item_price'].dtype

dtype('O')

#### Step 13.b. Create a lambda function and change the type of item price

In [ ]:
func = lambda x : float(x.replace('$', ''))
data['item_price'] = data.item_price.apply(func)

0     2.39
1     3.39
2     3.39
3     2.39
4    16.98
Name: item_price, dtype: float64

#### Step 13.c. Check the item price type

In [56]:
data.item_price.dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [71]:
data['revenue'] = (data['quantity'] * data['item_price'])
data['revenue'].sum()

39237.02

### Step 15. How many orders were made in the period?

In [60]:
data['quantity'].sum()

4972

### Step 16. What is the average revenue amount per order?

In [72]:
data.groupby('order_id')['revenue'].sum().mean()

21.39423118865867

### Step 17. How many different items are sold?

In [68]:
data.item_name.value_counts()

item_name
Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Steak Bowl                               211
Chips                                    211
Bottled Water                            162
Chicken Soft Tacos                       115
Chips and Fresh Tomato Salsa             110
Chicken Salad Bowl                       110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Crispy Tacos                      47
Chips and Tomatillo Green Chili Salsa     43
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        35
Chips and Tomatillo-Green Chili Salsa     31
Steak Salad Bowl                          29
Nantucket Nectar                          27
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        22
Izze                                      20
Chips and Tomatillo-Red Chili Salsa       20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Veggie Soft Tacos                          7
Carnitas Crispy Tacos                      7
Veggie Salad                               6
Carnitas Salad Bowl                        6
Burrito                                    6
Steak Salad                                4
Crispy Tacos                               2
Salad                                      2
Bowl                                       2
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Carnitas Salad                             1
Name: count, dtype: int64

In [ ]:
# observations and conclusions

### Download titanic CSV from internet and read the CSV file

### Step 1. Calculate the total number of missing data in each attribute

In [73]:
titanic = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/titanic.csv', sep=',')
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Step 2. Replace missing values with mean and median

In [91]:
gender_cat = titanic.groupby('Sex')
gender_mean = gender_cat.Age.mean()
for d, data in gender_cat:
    if d == 'male':
        titanic.loc[titanic['Sex'] == 'male', 'Age'] = titanic.loc[titanic['Sex'] == 'male', 'Age'].fillna(gender_mean['male'])
    else:
        titanic.loc[titanic['Sex'] == 'female', 'Age'] = titanic.loc[titanic['Sex'] == 'female', 'Age'].fillna(gender_mean['female'])

titanic['Age'].head(10)

0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
5    30.726645
6    54.000000
7     2.000000
8    27.000000
9    14.000000
Name: Age, dtype: float64

### Step 3. Replace missing values by category-wise mean (e.g., by gender or other criteria)

In [92]:
titanic['Age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    27.915709
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

### Step 4. Calculate the number of duplicate rows and remove duplicates

In [93]:
titanic.duplicated().sum()

0

Good Job